In [ ]:
import numpy as np
np.__version__

In [ ]:
summ = 0
for num in range(1,99999999):
    summ += num
summ

In [ ]:
sq = np.arange(1,99999999, dtype=np.int64)
sq.sum()

# Instant Array

In [ ]:
np.arange(1,100, 5)

In [ ]:
np.ones((2, 2, 2), dtype=np.int64)

In [ ]:
np.zeros((2,2))

In [ ]:
np.eye(5, 5, k=-3)

In [ ]:
np.empty((3,3))

In [ ]:
np.full((3,3), 0.1)

In [ ]:
np.linspace(10,40, 42)

In [ ]:
np.random.randint(0,100)

In [ ]:
np.random.randn(100)

In [ ]:
np.random.random(200)

# Types of Array


In [80]:
np.array([2,3,4,56,1,6534], dtype=np.int16)

array([   2,    3,    4,   56,    1, 6534], dtype=int16)

In [81]:
np.array([2,3,4,56,1,6534.98], dtype=np.float16)

array([2.000e+00, 3.000e+00, 4.000e+00, 5.600e+01, 1.000e+00, 6.536e+03],
      dtype=float16)

In [83]:
np.array([True, False, True, True, False], dtype=np.bool_)

array([ True, False,  True,  True, False])

In [84]:
np.array([2,3,4,56,1,6534], dtype=np.complex64)

array([2.000e+00+0.j, 3.000e+00+0.j, 4.000e+00+0.j, 5.600e+01+0.j,
       1.000e+00+0.j, 6.534e+03+0.j], dtype=complex64)

In [85]:
np.array(['apple', 'banana', 'guava', 'grapes'], dtype=np.string_)

array([b'apple', b'banana', b'guava', b'grapes'], dtype='|S6')

# NDarray Inspection

In [88]:
arr1 = np.ones((2, 2), dtype=np.int64)
arr1

array([[1, 1],
       [1, 1]], dtype=int64)

In [89]:
arr1.ndim

2

In [90]:
arr1.shape

(2, 2)

In [91]:
arr1.itemsize

8

In [92]:
arr1.size

4

In [93]:
arr1.dtype

dtype('int64')

# Slicing

In [94]:
arr2 = np.array(
    [
        [44, 22, 56, 79],
        [67, 76, 89, 79],
        [52, 45, 78, 79],
        [13, 53, 64, 88]
    ]
)

In [105]:
arr2[0, 1]
arr2[2:, 1:3]

array([[45, 78],
       [53, 64]])

In [106]:
arr2[1:3, 2:]

array([[89, 79],
       [78, 79]])

# Filtering

In [107]:
arr2

array([[44, 22, 56, 79],
       [67, 76, 89, 79],
       [52, 45, 78, 79],
       [13, 53, 64, 88]])

In [108]:
arr2 > 60

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True]])

In [109]:
arr2[arr2 > 60]

array([79, 67, 76, 89, 79, 78, 79, 64, 88])

In [111]:
arr2[(arr2 > 50) & (arr2 < 70)]

array([56, 67, 52, 53, 64])

In [112]:
arr2[(arr2%2 == 0)]

array([44, 22, 56, 76, 52, 78, 64, 88])

In [113]:
arr2[~arr2%2 == 0]

array([79, 67, 89, 79, 45, 79, 13, 53])

# Operator

In [119]:
arr3 = arr2//2
arr3

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]], dtype=int32)

In [120]:
arr2

array([[44, 22, 56, 79],
       [67, 76, 89, 79],
       [52, 45, 78, 79],
       [13, 53, 64, 88]])

In [121]:
arr2 + arr3

array([[ 66,  33,  84, 118],
       [100, 114, 133, 118],
       [ 78,  67, 117, 118],
       [ 19,  79,  96, 132]])

In [122]:
arr2 * arr3

array([[ 968,  242, 1568, 3081],
       [2211, 2888, 3916, 3081],
       [1352,  990, 3042, 3081],
       [  78, 1378, 2048, 3872]])

In [125]:
arr2 / arr3

array([[2.        , 2.        , 2.        , 2.02564103],
       [2.03030303, 2.        , 2.02272727, 2.02564103],
       [2.        , 2.04545455, 2.        , 2.02564103],
       [2.16666667, 2.03846154, 2.        , 2.        ]])

In [126]:
arr2 % arr3

array([[0, 0, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 0]], dtype=int32)

In [127]:
# Matrix multiplication
arr2 @ arr3

array([[ 3624,  4606,  6912,  8234],
       [ 6770,  7637, 11219, 12524],
       [ 5131,  6052,  9006, 10301],
       [ 4227,  5853,  8008,  8942]])

In [128]:
np.add(arr2, arr3)

array([[ 66,  33,  84, 118],
       [100, 114, 133, 118],
       [ 78,  67, 117, 118],
       [ 19,  79,  96, 132]])

In [129]:
np.multiply(arr2, arr3)

array([[ 968,  242, 1568, 3081],
       [2211, 2888, 3916, 3081],
       [1352,  990, 3042, 3081],
       [  78, 1378, 2048, 3872]])

In [130]:
np.matmul(arr2, arr3)

array([[ 3624,  4606,  6912,  8234],
       [ 6770,  7637, 11219, 12524],
       [ 5131,  6052,  9006, 10301],
       [ 4227,  5853,  8008,  8942]])

# Stats

In [132]:
arr3

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]], dtype=int32)

In [140]:
arr3.max(axis=1)
arr3.min(axis=1)

array([11, 33, 22,  6], dtype=int32)

In [144]:
arr3.mean()
arr3.mean(axis=1)
arr3.mean(axis=0)

array([21.75, 24.25, 35.75, 40.25])

In [145]:
arr3.std(axis=0)

array([9.90896059, 9.65336729, 6.17960355, 2.16506351])

In [147]:
arr3.var(axis=0)

array([9.90896059, 9.65336729, 6.17960355, 2.16506351])

In [150]:
np.cov(arr3)

array([[136.66666667,  15.66666667,  92.33333333, 110.        ],
       [ 15.66666667,  20.33333333,  26.66666667,  50.66666667],
       [ 92.33333333,  26.66666667,  77.66666667,  96.66666667],
       [110.        ,  50.66666667,  96.66666667, 252.        ]])

In [151]:
np.min(arr3, axis=0)

array([ 6, 11, 28, 39], dtype=int32)

In [152]:
arr3

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]], dtype=int32)

In [154]:
np.argmax(arr3, axis=0)

array([1, 1, 1, 3], dtype=int64)

In [155]:
np.argmin(arr3, axis=0)

array([3, 0, 0, 0], dtype=int64)

In [159]:
np.argsort(arr3)

array([[1, 0, 2, 3],
       [0, 1, 3, 2],
       [1, 0, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

# Saving and Loading Data

In [160]:
arr3

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]], dtype=int32)

In [164]:
# saving data
np.save('darr3.npy', arr3)

In [163]:
# Loading data
np.load('darr3.npy')

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]])

In [168]:
np.savez('arr3.npz', arrsq=arr3**2, arrcube=arr3**3)

In [169]:
file = np.load('arr3.npz')

In [170]:
file.files

['arrsq', 'arrcube']

In [171]:
file['arrsq']

array([[ 484,  121,  784, 1521],
       [1089, 1444, 1936, 1521],
       [ 676,  484, 1521, 1521],
       [  36,  676, 1024, 1936]])

In [172]:
file['arrcube']

array([[10648,  1331, 21952, 59319],
       [35937, 54872, 85184, 59319],
       [17576, 10648, 59319, 59319],
       [  216, 17576, 32768, 85184]])

In [173]:
np.savetxt('arr3.txt', arr3)

In [ ]:
# https://numpy.org/doc/stable/